// ─── Storefront Themes ───────────────────────────────────────────────────
// Each theme defines the visual identity of a customer-facing store.
// Store owners pick a theme from their MyShop control panel.
// The StorefrontPage reads the theme and applies it dynamically.

export const STOREFRONT_THEMES = [
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm orange tones — the ToGoGo classic',
    accent: '#FF6B35',
    accentHover: '#e85d2c',
    accentLight: 'rgba(255,107,53,0.10)',
    heroBg: 'bg-gradient-to-br from-[#FF6B35] to-[#FF8F5E]',
    headerBg: 'bg-white/95',
    headerText: 'text-gray-900',
    pageBg: 'bg-gray-50',
    cardBg: 'bg-white',
    cardBorder: '',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    textMuted: 'text-gray-400',
    badgeBg: 'bg-[#FF6B35]',
    footerBg: 'bg-white',
    preview: { bg: '#FFF7F2', accent: '#FF6B35', card: '#FFFFFF' },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Sleek dark mode with electric blue',
    accent: '#3B82F6',
    accentHover: '#2563EB',
    accentLight: 'rgba(59,130,246,0.10)',
    heroBg: 'bg-gradient-to-br from-[#1e3a5f] to-[#0f172a]',
    headerBg: 'bg-[#0f172a]/95',
    headerText: 'text-white',
    pageBg: 'bg-[#0f172a]',
    cardBg: 'bg-[#1e293b]',
    cardBorder: 'border border-white/[0.06]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-400',
    textMuted: 'text-slate-500',
    badgeBg: 'bg-[#3B82F6]',
    footerBg: 'bg-[#0f172a]',
    preview: { bg: '#0F172A', accent: '#3B82F6', card: '#1E293B' },
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Earthy greens for natural & organic brands',
    accent: '#16A34A',
    accentHover: '#15803D',
    accentLight: 'rgba(22,163,74,0.10)',
    heroBg: 'bg-gradient-to-br from-[#16A34A] to-[#4ADE80]',
    headerBg: 'bg-white/95',
    headerText: 'text-gray-900',
    pageBg: 'bg-[#F0FDF4]',
    cardBg: 'bg-white',
    cardBorder: '',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    textMuted: 'text-gray-400',
    badgeBg: 'bg-[#16A34A]',
    footerBg: 'bg-white',
    preview: { bg: '#F0FDF4', accent: '#16A34A', card: '#FFFFFF' },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft purple elegance for premium stores',
    accent: '#8B5CF6',
    accentHover: '#7C3AED',
    accentLight: 'rgba(139,92,246,0.10)',
    heroBg: 'bg-gradient-to-br from-[#8B5CF6] to-[#C4B5FD]',
    headerBg: 'bg-white/95',
    headerText: 'text-gray-900',
    pageBg: 'bg-[#FAF5FF]',
    cardBg: 'bg-white',
    cardBorder: '',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    textMuted: 'text-gray-400',
    badgeBg: 'bg-[#8B5CF6]',
    footerBg: 'bg-white',
    preview: { bg: '#FAF5FF', accent: '#8B5CF6', card: '#FFFFFF' },
  },
  {
    id: 'coral',
    name: 'Coral Reef',
    description: 'Vibrant pink tones for bold brands',
    accent: '#EC4899',
    accentHover: '#DB2777',
    accentLight: 'rgba(236,72,153,0.10)',
    heroBg: 'bg-gradient-to-br from-[#EC4899] to-[#F9A8D4]',
    headerBg: 'bg-white/95',
    headerText: 'text-gray-900',
    pageBg: 'bg-[#FDF2F8]',
    cardBg: 'bg-white',
    cardBorder: '',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    textMuted: 'text-gray-400',
    badgeBg: 'bg-[#EC4899]',
    footerBg: 'bg-white',
    preview: { bg: '#FDF2F8', accent: '#EC4899', card: '#FFFFFF' },
  },
]

export const DEFAULT_THEME_ID = 'sunset'

export function getThemeById(id) {
  return STOREFRONT_THEMES.find(t => t.id === id) || STOREFRONT_THEMES[0]
}
